default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: char-cleanup
        name: Special character cleanup
        entry: scripts/char_cleanup.py
        language: python
        # files: .*\.(py|md)
        # types_or: [text, python]
        files: .*\.md$
        types_or: [text]
        exclude: ^scripts/
        pass_filenames: true

      - id: pytest-check-fast
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
          -m not integration and not slow,
          --tb=short
        ]
        stages: [pre-commit]

      - id: pytest-check-all
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
            --cov=ether,
            --cov-report=xml,
            --cov-report=term-missing,
            --cov-report=html,
            --cov-fail-under=90,
            --strict-markers,
            --tb=short
        ]
        stages: [pre-push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-merge-conflict
      - id: debug-statements
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
        args: []


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [
          --ignore-missing-imports,
          --no-warn-unused-ignores  # pre-commit is isolated
        ]
